getwd()
iris
str(iris)
set.seed(123)
iris_mixed=iris[order(runif(150)),]
iris_train=iris_mixed[1:120,]
iris_test=iris_mixed[121:150,]
install.packages("nnet")
library(nnet)
install.packages("NeuralNetTools")
library(NeuralNetTools)
nn=nnet(species~.,data=iris_train,size-2)
plotnet(nn)
summary(nn)
nn_pre=predict(nn,iris_test[,1:4],type="class")
nn_pre
install.packages("caret")
library(caret)
length(nn_pre)
nn_pre1=as.factor(nn_pre)
nn_pre1
confusionMatrix(nn_pre1,iris_test[,5])
set.seed(345)
nn_imp=train(Species~.,data=iris_train,method="nnet")
plot(nn_imp)
plotnet(nn_imp)

set.seed(456)
nn_imp=train(Species~.,data=iris_train,method="nnet")
plot(nn_imp)
nn_imp=test(Species~.,data=iris_train,method="nnet")
plot(nn_imp)
plotnet(nn_imp)
nn_pre=predict(nn,iris_train[,1:4],type="class")
nn_prel=as.factor(nn_pre)
confusionMatrix(nn_prel,iris_train[,5])

plot(nn_imp)
plotnet(nn_imp)
